task_planer/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('tasks_board.urls'))
]

tasks_board/urls.py
from django.urls import path


from tasks_board.views import (
    all_tasks, sign_up, sign_in, sign_out, current_day, upcoming,
    add_task, task, change_status, edit_task, delete_task, completed_tasks,
    goal, add_goal, all_goals, edit_goal, delete_goal, back, profile,
    anonymous_user_home, chart
)


app_name = 'board'

urlpatterns = [
    path('signout', sign_out, name='sign_out'),
    path('signin/', sign_in, name='sign_in'),
    path('signup/', sign_up, name='sign_up'),
    path('', anonymous_user_home, name='anon_home'),
    path('today/', current_day, name='today'),
    path('tasks/', all_tasks, name='tasks'),
    path('add_task/', add_task, name='add_task'),
    path('upcoming/', upcoming, name='upcoming'),
    path('task/<int:task_id>', task, name='task'),
    path('change_status/<int:task_id>', change_status, name='change_status'),
    path('edit_task/<int:task_id>', edit_task, name='edit_task'),
    path('delete_task/<int:task_id>', delete_task, name='delete_task'),
    path('completed_tasks/', completed_tasks, name='completed_tasks'),
    path('goals', all_goals, name='goals'),
    path('goal/<str:goal_id>', goal, name='goal'),
    path('add_goal/', add_goal, name='add_goal'),
    path('edit_goal/<str:goal_id>', edit_goal, name='edit_goal'),
    path('delete_goal/<str:goal_id>', delete_goal, name='delete_goal'),
    path('back/', back, name='back'),
    path('profile/', profile, name='profile'),
    path('chart/<str:chart_name>', chart, name='chart'),

]

tasks_board/models.py
import datetime

from django.conf import settings
from django.db import models
from datetime import date


class Priority(models.IntegerChoices):
    LOW = 0, 'Low'
    NORMAL = 1, 'Normal'
    HIGH = 2, 'High'


class Goal(models.Model):
    title = models.CharField(max_length=128)
    priority = models.IntegerField(default=Priority.LOW, choices=Priority.choices)
    string_id = models.CharField(max_length=128)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.string_id = self.title.replace(" ", "").lower()
        super().save(force_insert, force_update, using, update_fields)

    @property
    def get_priority(self):
        for choice in Priority.choices:
            if self.priority in choice:
                return choice[1]

    @property
    def color(self):
        colors = {'Low': 'gray', 'Normal': 'yellow', 'High': 'red'}
        return colors[self.get_priority]

    @property
    def bootstrap_color(self):
        bootstrap_colors = {'Low': 'secondary', 'Normal': 'warning', 'High': 'danger'}
        return bootstrap_colors[self.get_priority]

    @property
    def tasks(self):
        tasks = DailyTask.objects.filter(owner=self.owner, goal=self, main_task=None)
        tasks = sorted(tasks, key=lambda t: (not t.status, t.day, t.priority), reverse=True)
        return tasks


class DailyTask(models.Model):
    title = models.CharField(max_length=128)
    priority = models.IntegerField(default=Priority.LOW, choices=Priority.choices)
    status = models.BooleanField(default=False)
    day = models.DateField(default=date.today())
    main_task = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)
    goal = models.ForeignKey(Goal, on_delete=models.SET_NULL, blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return f'{self.title}: {self.status}'

    @property
    def get_priority(self):
        for choice in Priority.choices:
            if self.priority in choice:
                return choice[1]

    @property
    def color(self):
        if self.status:
            return 'green'
        colors = {'Low': 'gray', 'Normal': 'yellow', 'High': 'red'}
        return colors[self.get_priority]

    @property
    def bootstrap_color(self):
        if self.status:
            return 'success'
        bootstrap_colors = {'Low': 'secondary', 'Normal': 'warning', 'High': 'danger'}
        return bootstrap_colors[self.get_priority]

    @property
    def sub_tasks(self):
        tasks = DailyTask.objects.filter(owner=self.owner, main_task=self)
        tasks = sorted(tasks, key=lambda t: (t.day, t.priority), reverse=True)
        return tasks

tasks_board/forms.py
from django.forms import ModelForm

tasks_board/views.py
import json

from django.conf.urls import url
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from datetime import date

from django.urls import reverse

from .models import Goal, DailyTask
from .business.business import save_task_form, change_task_status, save_goal_form
from .business.satistic import Statistic, GoalCategory


def anonymous_user_home(request):
    return render(request, 'tasks_board/not_auth_home.html')


@login_required
def all_tasks(request):
    request.session['return_page'] = 'board:tasks'
    tasks = DailyTask.objects.filter(main_task=None, status=False, owner=request.user)
    tasks = sorted(tasks, key=lambda t: (t.day, t.priority), reverse=True)
    goals = Goal.objects.all()

    return render(request, 'tasks_board/tasks.html', {'tasks': tasks, 'goals': goals})


@login_required
def current_day(request):
    request.session['return_page'] = 'board:today'
    tasks = DailyTask.objects.filter(day=date.today(), main_task=None, status=False, owner=request.user)
    tasks = sorted(tasks, key=lambda t: (t.day, t.priority), reverse=True)
    goals = Goal.objects.all()
    return render(request, 'tasks_board/today.html', {'tasks': tasks, 'goals': goals})


@login_required
def upcoming(request):
    return render(request, 'tasks_board/upcoming.html')


def sign_out(request):
    logout(request)
    return redirect('board:today')


def sign_up(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('board:today')
    else:
        form = UserCreationForm()
    return render(request, 'tasks_board/signup.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)
            return HttpResponse(json.dumps({'message': "Success"}), content_type='application/json')
        else:
            return HttpResponse(json.dumps({'message': "Denied"}), content_type='application/json')


@login_required
def task(request, task_id):
    task = DailyTask.objects.get(pk=task_id)
    goals = Goal.objects.all()
    request.session['previous_url'] = request.META['HTTP_REFERER']
    return render(request, 'tasks_board/task.html', {'task': task, 'goals': goals})


def add_task(request):
    if request.method == 'POST':
        result = save_task_form(request)
        return HttpResponse(result)


def change_status(request, task_id):
    task = DailyTask.objects.get(pk=task_id)
    change_task_status(task)
    return HttpResponse('ok')


def edit_task(request, task_id):
    task = DailyTask.objects.get(pk=task_id)
    if request.method == 'POST':
        result = save_task_form(request, task)
        return HttpResponse(result)


def delete_task(request, task_id):
    t = DailyTask.objects.get(pk=task_id)
    main_task = t.main_task
    t.delete()
    if main_task:
        return redirect('board:task', task_id=main_task.id)
    elif request.session['return_page']:
        return redirect(request.session['return_page'])
    return redirect('board:tasks')


@login_required
def completed_tasks(request):
    request.session['return_page'] = 'board:completed_tasks'
    tasks = DailyTask.objects.filter(status=True, main_task=None, owner=request.user)
    tasks = sorted(tasks, key=lambda t: (t.day, t.priority), reverse=True)
    goals = Goal.objects.all()
    return render(request, 'tasks_board/completed_tasks.html', {'tasks': tasks, 'goals': goals})


@login_required
def goal(request, goal_id):
    if request.method == 'GET':
        request.session['return_page'] = reverse('board:goal', kwargs={'goal_id': goal_id})
        goal = Goal.objects.get(pk=goal_id)
        goals = Goal.objects.all()
        return render(request, 'tasks_board/goal.html', {'goal': goal, 'goals': goals})


@login_required
def all_goals(request):
    if request.method == 'GET':
        request.session['return_page'] = 'board:goals'
        goals = Goal.objects.filter(owner=request.user)
        goals = sorted(goals, key=lambda g: g.priority, reverse=True)
        return render(request, 'tasks_board/goals.html', {'goals': goals})


def add_goal(request):
    if request.method == 'POST':
        result = save_goal_form(request)
        return HttpResponse(result)


def delete_goal(request, goal_id):
    Goal.objects.get(pk=goal_id).delete()
    return redirect('board:goals')


def edit_goal(request, goal_id):
    goal = Goal.objects.get(pk=goal_id)
    if request.method == 'POST':
        result = save_goal_form(request, goal)
        return HttpResponse(result)


def back(request):
    return redirect(request.session['return_page'])


@login_required
def profile(request):
    return render(request, 'tasks_board/profile.html', {'statistic': Statistic(request)})


def chart(request, chart_name):
    if chart_name == 'todaytasks':
        return HttpResponse(Statistic(request).today_tasks.modal_html)
    elif chart_name == 'alltasks':
        return HttpResponse(Statistic(request).all_tasks.modal_html)
    else:
        return HttpResponse(GoalCategory(chart_name).modal_html)

tasks_board/templates/tasks_board/add_goal.html
{% load static %}
{% csrf_token %}
<div class="modal" id="{% block modal_id %}add_goal{% endblock %}">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">

            <div class="modal-header">
                <h2 class="text-white">Add goal</h2>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <div class="form-group mb-0">
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <span class="input-group-text"> Title </span>
                        </div>
                        <input type="text" class="form-control title" name="title" placeholder="Goal"
                            value="{% block goal_title %}{% endblock %}"
                        >
                    </div>

                </div>
                <span id="title_error" class="text-danger"></span>

                <div class="form-group mt-3">
                    <select class="custom-select priority" name="priority">
                        {% block goal_priority %}
                            <option value=0>Low</option>
                            <option value=1>Normal</option>
                            <option value=2>High</option>
                        {% endblock %}
                    </select>
                </div>

            </div>

            <div class="modal-footer">
                <div class="form-group mx-auto">
                    <input type="submit" onclick="
                            {% block goal_function %}add_goal({% url 'board:add_goal' %}, '#add_goal'){% endblock %}"
                           value="Save" class="btn btn-outline-primary add_task_bth" style="width: 100px">
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'tasks_board/js/base.js' %}"></script>

tasks_board/templates/tasks_board/add_task.html
{% load static %}
{% csrf_token %}
<div class="modal" id=
        {% block modal_id %}
            "add_task"
        {% endblock %}
     >
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h2 class="text-white">Add task</h2>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body">
                <div class="form-group mb-0">
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <span class="input-group-text"> Title </span>
                        </div>
                        <input type="text" class="form-control title" name="title" placeholder="Task"
                            {% block task_title %}
                            {% endblock %}
                        >
                    </div>
                </div>
                <span id="title_error" class="text-danger"></span>


                <div class="form-group mt-3 mb-0">
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <span class="input-group-text"> Date </span>
                        </div>
                        <input type="text" class="form-control date" name="date"
                                {% block task_day %}
                                    {% if main_task %}
                                        value="{{ main_task.day.isoformat }}"
                                    {% else %}
                                        value="{% now "Y-m-d" %}"
                                    {% endif %}
                                {% endblock %}
                        >
                    </div>
                    <span id="date_error" class="text-danger ml-auto"></span>
                </div>

                <div class="form-group mt-3">
                    <select class="custom-select priority" name="priority">
                        {% block task_priority %}
                            <option selected value="">Priority</option>
                            <option value=0>Low</option>
                            <option value=1>Normal</option>
                            <option value=2>High</option>
                        {% endblock %}
                    </select>
                </div>

                <div class="form-group">
                    <select class="custom-select goal" name="goal">
                        {% block goals %}
                            <option selected value="">Goal</option>
                            {% for goal in goals %}
                                <option value={{ goal.id }}>{{ goal }}</option>
                            {% endfor %}
                        {% endblock %}
                    </select>
                </div>
                <input class="main_task" type="hidden" name="main_task" value={{ main_task.id }}>
            </div>

            <div class="modal-footer">
                <div class="form-group mx-auto">
                    <input type="submit"
                           {% block task_function %}
                               onclick="add_task({% url 'board:add_task' %}, '#add_task')"
                           {% endblock %}
                           value="Save" class="btn btn-outline-primary add_task_bth" style="width: 100px">
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'tasks_board/js/base.js' %}"></script>

tasks_board/templates/tasks_board/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'tasks_board/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'tasks_board/css/tasks.css' %}">
    <link rel="stylesheet" href="{% static 'tasks_board/css/task.css' %}">
    {% block head %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% csrf_token %}
    <nav class="navbar navbar-expand bg-dark navbar-dark fixed-top top-nav py-2 px-5">
        <a class="navbar-brand ml-3" href="{% url 'board:today' %}">Planer</a>

        {% block navi %}
        {% endblock %}

        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-3">
            {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btb dropdown-toggle profile" data-toggle="dropdown"></button>
                    <div class="dropdown-menu dropdown-menu-right bg-secondary mt-2 p-1">
                        <a class="dropdown-item btn text-white" href="{% url 'board:profile' %}">
                            Profile
                        </a>
                        <a class="dropdown-item btn text-white" href="{% url 'board:sign_out' %}">
                        Log out
                        </a>
                    </div>
                </div>
            {% else %}
                <button class="btn btn-outline-primary" data-toggle="modal" data-target="#login_modal">
                    Login
                </button>
            {% endif %}
            </li>
        </ul>
    </nav>


    <div class="left-nav bg-dark">
        <nav class="navbar p-0 pt-5">
            <button class="pl-4 navbar-toggler btn btn-dark"
                    data-toggle="collapse" data-target="#goals_nav">
                <svg height="20px" width="20px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="crosshairs" class="svg-inline--fa fa-crosshairs fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path fill="currentColor" d="M500 224h-30.364C455.724 130.325 381.675 56.276 288 42.364V12c0-6.627-5.373-12-12-12h-40c-6.627 0-12 5.373-12 12v30.364C130.325 56.276 56.276 130.325 42.364 224H12c-6.627 0-12 5.373-12 12v40c0 6.627 5.373 12 12 12h30.364C56.276 381.675 130.325 455.724 224 469.636V500c0 6.627 5.373 12 12 12h40c6.627 0 12-5.373 12-12v-30.364C381.675 455.724 455.724 381.675 469.636 288H500c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12zM288 404.634V364c0-6.627-5.373-12-12-12h-40c-6.627 0-12 5.373-12 12v40.634C165.826 392.232 119.783 346.243 107.366 288H148c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12h-40.634C119.768 165.826 165.757 119.783 224 107.366V148c0 6.627 5.373 12 12 12h40c6.627 0 12-5.373 12-12v-40.634C346.174 119.768 392.217 165.757 404.634 224H364c-6.627 0-12 5.373-12 12v40c0 6.627 5.373 12 12 12h40.634C392.232 346.174 346.243 392.217 288 404.634zM288 256c0 17.673-14.327 32-32 32s-32-14.327-32-32c0-17.673 14.327-32 32-32s32 14.327 32 32z"></path>
                </svg>
                   Goals
                </button>
            <div class="collapse navbar-collapse mt-2 show" id="goals_nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="pl-5 nav-link btn btn-dark"
                           href="{% url 'board:goals' %}">All goals</a>
                    </li>
                </ul>
            </div>
            <button class="pl-4 navbar-toggler btn btn-dark"
                    data-toggle="collapse" data-target="#tasks_nav">
                <svg height="20px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="thumbtack" class="svg-inline--fa fa-thumbtack fa-w-12" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
                    <path fill="currentColor" d="M298.028 214.267L285.793 96H328c13.255 0 24-10.745 24-24V24c0-13.255-10.745-24-24-24H56C42.745 0 32 10.745 32 24v48c0 13.255 10.745 24 24 24h42.207L85.972 214.267C37.465 236.82 0 277.261 0 328c0 13.255 10.745 24 24 24h136v104.007c0 1.242.289 2.467.845 3.578l24 48c2.941 5.882 11.364 5.893 14.311 0l24-48a8.008 8.008 0 0 0 .845-3.578V352h136c13.255 0 24-10.745 24-24-.001-51.183-37.983-91.42-85.973-113.733z"></path>
                </svg>
                Tasks
            </button>
            <div class="collapse navbar-collapse show mt-2" id="tasks_nav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="pl-5 nav-link btn btn-dark"
                           href="{% url 'board:tasks' %}">All Tasks</a>
                    </li>
                    <li class="nav-item">
                        <a class="pl-5 nav-link btn btn-dark"
                           href="{% url 'board:today'%}">Today</a>
                    </li>
                    <li class="nav-item">
                        <a class="pl-5 nav-link btn btn-dark"
                           href="{% url 'board:completed_tasks' %}">Completed tasks</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="body">
        {% block button_back %}
            <a class="btn bth-outline-primary ml-5 mt-5" href="{% url 'board:back' %}">
                <h5>&#8678;  back</h5>
            </a>
        {% endblock %}
        {% block body %}
        {% endblock %}
    </div>



    <div class="modal" id="login_modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Authorization</h3>
                    <button class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="username">Login:</label>
                        <input class="form-control" type="text" name='username' id="username" placeholder="ivan">
                    </div>
                    <div class="form-group">
                        <label for="password">Password:</label>
                        <input class="form-control" type="password" name='password' id="password">
                    </div>
                    <div id="login_error" class="text-danger font-weight-bold text-center"></div>
                </div>
                <div class="modal-footer">
                    <div class="mr-auto">
                        <button type="button" class="btn btn-outline-success mr-2"
                                onclick="login_user('{% url 'board:sign_in' %}', '{% url 'board:today' %}')">Sign In</button>
                        <a href="{% url 'board:sign_up' %}">Sigu up</a>
                    </div>
                    <button class="btn btn-outline-danger" data-dismiss="modal">Close</button>

                </div>
            </div>
        </div>
    </div>


    <script src="{% static 'tasks_board/js/base.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

tasks_board/templates/tasks_board/edit_task.html
{% extends 'tasks_board/add_task.html' %}

{% block modal_id %}
    edit_task
{% endblock %}


{% block task_status %}
    {% if task.status %}
        checked
    {% endif %}
{% endblock %}

{% block task_title %}
    value="{{ task.title }}"
{% endblock %}

{% block task_day %}
    value="{{ task.day.isoformat }}"
{% endblock %}


{% block task_priority %}
    <option value=0
        {% if task.priority == 0 %}
            selected
        {% endif %}
    >Low</option>
    <option value=1
        {% if task.priority == 1 %}
            selected
        {% endif %}
    >Normal</option>
    <option value=2
        {% if task.priority == 2 %}
            selected
        {% endif %}
    >High</option>
{% endblock %}


{% block goals %}
    {% for goal in goals %}
        <option value={{ goal.id }}
            {% if goal.id == task.goal.id %}
                selected
            {% endif %}
        >{{ goal }}</option>
    {% endfor %}
{% endblock %}


{% block task_function %}
    onclick="add_task('{% url 'board:edit_task' task.id %}', '#edit_task')"
{% endblock %}

tasks_board/templates/tasks_board/goal_column.html
<div class="task_link d-flex">
    <a class="text-dark d-flex flex-fill" href="{% url 'board:goal' goal.id %}">
        <div class="ml-4 mt-3">
            <svg height="25px" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="crosshairs" class="svg-inline--fa fa-crosshairs fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path fill="{{ goal.color }}" d="M500 224h-30.364C455.724 130.325 381.675 56.276 288 42.364V12c0-6.627-5.373-12-12-12h-40c-6.627 0-12 5.373-12 12v30.364C130.325 56.276 56.276 130.325 42.364 224H12c-6.627 0-12 5.373-12 12v40c0 6.627 5.373 12 12 12h30.364C56.276 381.675 130.325 455.724 224 469.636V500c0 6.627 5.373 12 12 12h40c6.627 0 12-5.373 12-12v-30.364C381.675 455.724 455.724 381.675 469.636 288H500c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12zM288 404.634V364c0-6.627-5.373-12-12-12h-40c-6.627 0-12 5.373-12 12v40.634C165.826 392.232 119.783 346.243 107.366 288H148c6.627 0 12-5.373 12-12v-40c0-6.627-5.373-12-12-12h-40.634C119.768 165.826 165.757 119.783 224 107.366V148c0 6.627 5.373 12 12 12h40c6.627 0 12-5.373 12-12v-40.634C346.174 119.768 392.217 165.757 404.634 224H364c-6.627 0-12 5.373-12 12v40c0 6.627 5.373 12 12 12h40.634C392.232 346.174 346.243 392.217 288 404.634zM288 256c0 17.673-14.327 32-32 32s-32-14.327-32-32c0-17.673 14.327-32 32-32s32 14.327 32 32z"></path>
            </svg>
        </div>
        <div class="flex-fill">
            <div class="d-flex justify-content-between mt-2 ml-5 header">
                <h6>{{ goal.title }}</h6>
            </div>
        </div>
    </a>
</div>
<hr>

tasks_board/templates/tasks_board/signup.html
{% extends 'tasks_board/base.html' %}

{% block button_back %}
{% endblock %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'tasks_board/css/auth.css' %}">
{% endblock %}

{% block title %} Sign up {% endblock %}

{% block body %}
    <div class="container body_block py-5">
        <div class="signup_container text-center font-weight-bold border border-info rounded py-5">
            <form class="mx-auto signup_form" method="post" action="{% url 'board:sign_up' %}">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label_tag }}
                        <input class="form-control" name="{{ field.html_name }}" type="{{ field.widget_type }}"/>
                    </div>
                    {% if field.errors %}
                        <div class="text-center text-danger">
                            <ul>
                                {% for error in field.errors %}
                                    <li>
                                    {{ error }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% endfor %}
                <input class="btn btn-outline-success" type="submit" value="Sign up">
            </form>
        </div>
    </div>
{% endblock %}

tasks_board/templates/tasks_board/task_status.html
{% load static %}
<span class="div_status mt-3" onclick="change_status('{% url 'board:change_status' task.id %}')">
    {% if task.status %}
        <svg height="30px" aria-hidden="true" focusable="false" data-prefix="far" data-icon="check-circle" class="svg-inline--fa fa-check-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill="green" d="M256 8C119.033 8 8 119.033 8 256s111.033 248 248 248 248-111.033 248-248S392.967 8 256 8zm0 48c110.532 0 200 89.451 200 200 0 110.532-89.451 200-200 200-110.532 0-200-89.451-200-200 0-110.532 89.451-200 200-200m140.204 130.267l-22.536-22.718c-4.667-4.705-12.265-4.736-16.97-.068L215.346 303.697l-59.792-60.277c-4.667-4.705-12.265-4.736-16.97-.069l-22.719 22.536c-4.705 4.667-4.736 12.265-.068 16.971l90.781 91.516c4.667 4.705 12.265 4.736 16.97.068l172.589-171.204c4.704-4.668 4.734-12.266.067-16.971z"></path>
        </svg>
    {% else %}
        <svg height="30px" aria-hidden="true" focusable="false" data-prefix="far" data-icon="circle" class="svg-inline--fa fa-circle fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
            <path fill={{ task.color }} d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm0 448c-110.5 0-200-89.5-200-200S145.5 56 256 56s200 89.5 200 200-89.5 200-200 200z"></path>
        </svg>

    {% endif %}
</span>

tasks_board/templates/tasks_board/upcoming.html
{% extends 'tasks_board/base.html' %}


{% block body %}
<h1>Upcoming</h1>
{% endblock %}